create or replace table
    edwprodhh.iso.claimant_match_return
as
with MO02 as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_ma03,
                index_mo02,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     2)),    '')     as role_in_the_claim,
                nullif(trim(substring(response_line,    13,     1)),    '')     as individual_business_indicator,
                nullif(trim(substring(response_line,    14,     70)),   '')     as business_name,
                nullif(trim(substring(response_line,    14,     30)),   '')     as last_name,
                nullif(trim(substring(response_line,    44,     20)),   '')     as first_name,
                nullif(trim(substring(response_line,    64,     20)),   '')     as middle_name,
                nullif(trim(substring(response_line,    84,     8)),    '')     as date_of_birth_dob,
                nullif(trim(substring(response_line,    92,     1)),    '')     as gender,
                nullif(trim(substring(response_line,    93,     9)),    '')     as social_security_number_ssn,
                nullif(trim(substring(response_line,    102,    1)),    '')     as more_match_indicator,
                nullif(trim(substring(response_line,    103,    1)),    '')     as ssn_code,
                nullif(trim(substring(response_line,    104,    4)),    '')     as ssn_issued_from_date,
                nullif(trim(substring(response_line,    108,    4)),    '')     as ssn_issued_to_date,
                nullif(trim(substring(response_line,    112,    2)),    '')     as ssn_issuing_state,
                nullif(trim(substring(response_line,    114,    30)),   '')     as death_master_last_name,
                nullif(trim(substring(response_line,    144,    20)),   '')     as death_master_first_name,
                nullif(trim(substring(response_line,    164,    8)),    '')     as date_of_death,
                nullif(trim(substring(response_line,    172,    25)),   '')     as city_of_death,
                nullif(trim(substring(response_line,    197,    2)),    '')     as state_of_death,
                nullif(trim(substring(response_line,    199,    9)),    '')     as tax_identification_number_tin,
                nullif(trim(substring(response_line,    208,    1)),    '')     as filler,
                nullif(trim(substring(response_line,    209,    1)),    '')     as tin_code,
                nullif(trim(substring(response_line,    210,    25)),   '')     as tin_issuing_city,
                nullif(trim(substring(response_line,    235,    2)),    '')     as tin_issuing_state,
                nullif(trim(substring(response_line,    237,    20)),   '')     as drivers_license_number,
                nullif(trim(substring(response_line,    257,    2)),    '')     as drivers_license_state,
                nullif(trim(substring(response_line,    259,    50)),   '')     as occupation,
                nullif(trim(substring(response_line,    309,    15)),   '')     as medical_professional_license,
                nullif(trim(substring(response_line,    324,    50)),   '')     as address_information_line_1,
                nullif(trim(substring(response_line,    374,    50)),   '')     as address_information_line_2,
                nullif(trim(substring(response_line,    424,    25)),   '')     as city,
                nullif(trim(substring(response_line,    449,    2)),    '')     as state,
                nullif(trim(substring(response_line,    451,    9)),    '')     as postal_code,
                nullif(trim(substring(response_line,    460,    3)),    '')     as country_code,
                nullif(trim(substring(response_line,    463,    10)),   '')     as home_telephone,
                nullif(trim(substring(response_line,    473,    1)),    '')     as more_match_indicator_2,
                nullif(trim(substring(response_line,    474,    10)),   '')     as business_telephone,
                nullif(trim(substring(response_line,    484,    1)),    '')     as filler,
                nullif(trim(substring(response_line,    485,    10)),   '')     as cellular_telephone,
                nullif(trim(substring(response_line,    495,    1)),    '')     as more_match_indicator_3,
                nullif(trim(substring(response_line,    496,    10)),   '')     as pager_number,
                nullif(trim(substring(response_line,    506,    7)),    '')     as pager_pin

    from        edwprodhh.iso.response_flat
    where       record_type = 'MO02'
)
, MEX2 as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_ma03,
                index_mo02,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     1)),    '')     as party_subject_to_siu_investigation,
                nullif(trim(substring(response_line,    12,     1)),    '')     as was_claim_or_part_of_claim_for_this_party_not_paid_after_investigation,
                nullif(trim(substring(response_line,    13,     1)),    '')     as was_party_subject_to_an_enforcement_action_criminal_indictment_professional_disciplinary_action,
                nullif(trim(substring(response_line,    14,     1)),    '')     as does_claim_for_this_party_meet_criteria_for_fraud_bureau_reporting,
                nullif(trim(substring(response_line,    15,     1)),    '')     as filler,
                nullif(trim(substring(response_line,    16,     8)),    '')     as date_of_death,
                nullif(trim(substring(response_line,    24,     50)),   '')     as email_address,
                nullif(trim(substring(response_line,    74,     2)),    '')     as drivers_license_class,
                nullif(trim(substring(response_line,    76,     201)),  '')     as filler,
                nullif(trim(substring(response_line,    277,    1)),    '')     as was_driver_distracted,
                nullif(trim(substring(response_line,    278,    1)),    '')     as filler,
                nullif(trim(substring(response_line,    279,    234)),  '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MEX2'
)
, MK02 as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_ma03,
                index_mo02,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     1)),    '')     as individual_business_indicator,
                nullif(trim(substring(response_line,    12,     70)),   '')     as business_name,
                nullif(trim(substring(response_line,    12,     30)),   '')     as last_name,
                nullif(trim(substring(response_line,    42,     20)),   '')     as first_name,
                nullif(trim(substring(response_line,    62,     20)),   '')     as middle_name,
                nullif(trim(substring(response_line,    82,     8)),    '')     as date_of_birth_dob,
                nullif(trim(substring(response_line,    90,     1)),    '')     as gender,
                nullif(trim(substring(response_line,    91,     9)),    '')     as social_security_number_ssn,
                nullif(trim(substring(response_line,    100,    1)),    '')     as more_match_indicator_4,
                nullif(trim(substring(response_line,    101,    1)),    '')     as ssn_code,
                nullif(trim(substring(response_line,    102,    4)),    '')     as ssn_issued_from_date,
                nullif(trim(substring(response_line,    106,    4)),    '')     as ssn_issued_to_date,
                nullif(trim(substring(response_line,    110,    2)),    '')     as ssn_issuing_state,
                nullif(trim(substring(response_line,    112,    9)),    '')     as tax_identification_number_tin,
                nullif(trim(substring(response_line,    121,    1)),    '')     as filler,
                nullif(trim(substring(response_line,    122,    1)),    '')     as tin_code,
                nullif(trim(substring(response_line,    123,    4)),    '')     as tin_issued_from_date,
                nullif(trim(substring(response_line,    148,    4)),    '')     as tin_issued_to_date,
                nullif(trim(substring(response_line,    150,    2)),    '')     as tin_issuing_state,
                nullif(trim(substring(response_line,    165,    50)),   '')     as address_information_line_1,
                nullif(trim(substring(response_line,    215,    50)),   '')     as address_information_line_2,
                nullif(trim(substring(response_line,    265,    25)),   '')     as city,
                nullif(trim(substring(response_line,    290,    2)),    '')     as state,
                nullif(trim(substring(response_line,    292,    9)),    '')     as postal_code,
                nullif(trim(substring(response_line,    301,    3)),    '')     as country_code,
                nullif(trim(substring(response_line,    304,    1)),    '')     as filler,
                nullif(trim(substring(response_line,    305,    10)),   '')     as home_telephone,
                nullif(trim(substring(response_line,    315,    1)),    '')     as more_match_indicator_5,
                nullif(trim(substring(response_line,    316,    10)),   '')     as business_telephone,
                nullif(trim(substring(response_line,    326,    1)),    '')     as filler,
                nullif(trim(substring(response_line,    327,    10)),   '')     as cell_telephone,
                nullif(trim(substring(response_line,    337,    1)),    '')     as more_match_indicator_6,
                nullif(trim(substring(response_line,    338,    50)),   '')     as email_address_of_alias_aka,
                nullif(trim(substring(response_line,    388,    20)),   '')     as drivers_license_number,
                nullif(trim(substring(response_line,    408,    2)),    '')     as drivers_license_state,
                nullif(trim(substring(response_line,    410,    2)),    '')     as drivers_license_class,
                nullif(trim(substring(response_line,    412,    101)),  '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MK02'
)
, MP02 as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_ma03,
                index_mo02,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     55)),   '')     as adjusting_company_name,
                nullif(trim(substring(response_line,    66,     30)),   '')     as adjuster_last_name,
                nullif(trim(substring(response_line,    96,     20)),   '')     as adjuster_first_name,
                nullif(trim(substring(response_line,    116,    20)),   '')     as adjuster_middle_initial_name,
                nullif(trim(substring(response_line,    136,    10)),   '')     as adjuster_telephone_number,
                nullif(trim(substring(response_line,    146,    4)),    '')     as loss_type,
                nullif(trim(substring(response_line,    150,    3)),    '')     as claim_status,
                nullif(trim(substring(response_line,    153,    16)),   '')     as mortgage_loan_number,
                nullif(trim(substring(response_line,    169,    1)),    '')     as suit_indicator,
                nullif(trim(substring(response_line,    170,    11)),   '')     as building,
                nullif(trim(substring(response_line,    181,    11)),   '')     as contents,
                nullif(trim(substring(response_line,    192,    11)),   '')     as use_and_occupancy,
                nullif(trim(substring(response_line,    203,    11)),   '')     as stock,
                nullif(trim(substring(response_line,    214,    11)),   '')     as other,
                nullif(trim(substring(response_line,    225,    11)),   '')     as building_2,
                nullif(trim(substring(response_line,    236,    11)),   '')     as contents_2,
                nullif(trim(substring(response_line,    247,    11)),   '')     as use_and_occupancy_2,
                nullif(trim(substring(response_line,    258,    11)),   '')     as stock_2,
                nullif(trim(substring(response_line,    269,    11)),   '')     as other_2,
                nullif(trim(substring(response_line,    280,    11)),   '')     as building_3,
                nullif(trim(substring(response_line,    291,    11)),   '')     as contents_3,
                nullif(trim(substring(response_line,    302,    11)),   '')     as use_and_occupancy_3,
                nullif(trim(substring(response_line,    313,    11)),   '')     as stock_3,
                nullif(trim(substring(response_line,    324,    11)),   '')     as other_3,
                nullif(trim(substring(response_line,    335,    11)),   '')     as building_4,
                nullif(trim(substring(response_line,    346,    11)),   '')     as contents_4,
                nullif(trim(substring(response_line,    357,    11)),   '')     as use_and_occupancy_4,
                nullif(trim(substring(response_line,    368,    11)),   '')     as stock_4,
                nullif(trim(substring(response_line,    379,    11)),   '')     as other_4,
                nullif(trim(substring(response_line,    390,    1)),    '')     as type_of_property,
                nullif(trim(substring(response_line,    391,    35)),   '')     as other_property_description,
                nullif(trim(substring(response_line,    426,    1)),    '')     as vacant_under_construction_indicator,
                nullif(trim(substring(response_line,    427,    1)),    '')     as incendiary_fire_flag,
                nullif(trim(substring(response_line,    428,    1)),    '')     as location_of_theft,
                nullif(trim(substring(response_line,    429,    1)),    '')     as audio_visual,
                nullif(trim(substring(response_line,    430,    1)),    '')     as art_antique,
                nullif(trim(substring(response_line,    431,    1)),    '')     as cash,
                nullif(trim(substring(response_line,    432,    1)),    '')     as clothing,
                nullif(trim(substring(response_line,    433,    1)),    '')     as computer_equipment,
                nullif(trim(substring(response_line,    434,    1)),    '')     as furs,
                nullif(trim(substring(response_line,    435,    1)),    '')     as guns,
                nullif(trim(substring(response_line,    436,    1)),    '')     as jewelry,
                nullif(trim(substring(response_line,    437,    1)),    '')     as silverware,
                nullif(trim(substring(response_line,    438,    1)),    '')     as sports_equipment,
                nullif(trim(substring(response_line,    439,    1)),    '')     as tools,
                nullif(trim(substring(response_line,    440,    1)),    '')     as office_equipment,
                nullif(trim(substring(response_line,    441,    1)),    '')     as other_5,
                nullif(trim(substring(response_line,    442,    8)),    '')     as date_claim_closed,
                nullif(trim(substring(response_line,    450,    1)),    '')     as property_scheduled_indicator,
                nullif(trim(substring(response_line,    451,    35)),   '')     as property_scheduled_description,
                nullif(trim(substring(response_line,    486,    1)),    '')     as content_theft_type,
                nullif(trim(substring(response_line,    487,    26)),   '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MP02'
)
, MP14 as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_ma03,
                index_mo02,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     50)),   '')     as adjuster_email_address,
                nullif(trim(substring(response_line,    61,     41)),   '')     as filler,
                nullif(trim(substring(response_line,    102,    411)),  '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MP14'
)
, MSP2 as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_ma03,
                index_mo02,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     2)),    '')     as role_in_the_claim,
                nullif(trim(substring(response_line,    13,     1)),    '')     as individual_business_indicator,
                nullif(trim(substring(response_line,    14,     70)),   '')     as business_name,
                nullif(trim(substring(response_line,    14,     30)),   '')     as last_name,
                nullif(trim(substring(response_line,    44,     20)),   '')     as first_name,
                nullif(trim(substring(response_line,    64,     20)),   '')     as middle_name,
                nullif(trim(substring(response_line,    84,     8)),    '')     as date_of_birth_dob,
                nullif(trim(substring(response_line,    92,     1)),    '')     as gender,
                nullif(trim(substring(response_line,    93,     9)),    '')     as social_security_number_ssn,
                nullif(trim(substring(response_line,    102,    1)),    '')     as ssn_code,
                nullif(trim(substring(response_line,    103,    4)),    '')     as ssn_issued_from_date,
                nullif(trim(substring(response_line,    107,    4)),    '')     as ssn_issued_to_date,
                nullif(trim(substring(response_line,    111,    2)),    '')     as ssn_issuing_state,
                nullif(trim(substring(response_line,    113,    9)),    '')     as tax_identification_number_tin,
                nullif(trim(substring(response_line,    122,    1)),    '')     as tin_code,
                nullif(trim(substring(response_line,    123,    25)),   '')     as tin_issuing_city,
                nullif(trim(substring(response_line,    148,    2)),    '')     as tin_issuing_state,
                nullif(trim(substring(response_line,    150,    20)),   '')     as drivers_license_number,
                nullif(trim(substring(response_line,    170,    2)),    '')     as drivers_license_state,
                nullif(trim(substring(response_line,    172,    15)),   '')     as medical_professional_license,
                nullif(trim(substring(response_line,    187,    50)),   '')     as address_information_line_1,
                nullif(trim(substring(response_line,    237,    50)),   '')     as address_information_line_2,
                nullif(trim(substring(response_line,    287,    25)),   '')     as city,
                nullif(trim(substring(response_line,    312,    2)),    '')     as state,
                nullif(trim(substring(response_line,    314,    9)),    '')     as postal_code,
                nullif(trim(substring(response_line,    323,    3)),    '')     as country_code,
                nullif(trim(substring(response_line,    326,    10)),   '')     as home_telephone,
                nullif(trim(substring(response_line,    336,    10)),   '')     as business_telephone,
                nullif(trim(substring(response_line,    346,    10)),   '')     as cell_telephone,
                nullif(trim(substring(response_line,    356,    10)),   '')     as pager_number,
                nullif(trim(substring(response_line,    366,    7)),    '')     as pager_pin,
                nullif(trim(substring(response_line,    373,    8)),    '')     as date_of_first_doctors_visit,
                nullif(trim(substring(response_line,    381,    132)),  '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MSP2'
)
, MV09 as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_ma03,
                index_mo02,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     20)),   '')     as vin_of_salvaged_vehicle,
                nullif(trim(substring(response_line,    31,     1)),    '')     as more_match_indicator,
                nullif(trim(substring(response_line,    32,     1)),    '')     as vin_missing_indicator,
                nullif(trim(substring(response_line,    33,     1)),    '')     as engine_missing_indicator,
                nullif(trim(substring(response_line,    34,     1)),    '')     as transmission_missing_indicator,
                nullif(trim(substring(response_line,    35,     8)),    '')     as date_of_salvage,
                nullif(trim(substring(response_line,    43,     11)),   '')     as actual_cash_value_prior_to_loss,
                nullif(trim(substring(response_line,    54,     11)),   '')     as value_received_for_salvage,
                nullif(trim(substring(response_line,    65,     11)),   '')     as appraised_value_of_salvage,
                nullif(trim(substring(response_line,    76,     1)),    '')     as owner_retaining_salvage_indicator,
                nullif(trim(substring(response_line,    77,     1)),    '')     as individual_business_indicator,
                nullif(trim(substring(response_line,    78,     70)),   '')     as buyers_business_name,
                nullif(trim(substring(response_line,    78,     30)),   '')     as buyers_last_name,
                nullif(trim(substring(response_line,    108,    20)),   '')     as buyers_first_name,
                nullif(trim(substring(response_line,    128,    20)),   '')     as buyers_middle_name,
                nullif(trim(substring(response_line,    148,    50)),   '')     as buyers_address_line_1,
                nullif(trim(substring(response_line,    198,    50)),   '')     as buyers_address_line_2,
                nullif(trim(substring(response_line,    248,    25)),   '')     as buyers_city,
                nullif(trim(substring(response_line,    273,    2)),    '')     as buyers_state,
                nullif(trim(substring(response_line,    275,    9)),    '')     as postal_code,
                nullif(trim(substring(response_line,    284,    3)),    '')     as country_code,
                nullif(trim(substring(response_line,    287,    10)),   '')     as business_telephone,
                nullif(trim(substring(response_line,    297,    20)),   '')     as filler,
                nullif(trim(substring(response_line,    317,    20)),   '')     as failed_vin,
                nullif(trim(substring(response_line,    337,    176)),  '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MV09'
)
select      MO02.response_id,
            MO02.index_MA01,
            MO02.index_MA03,
            MO02.index_MO02,

            MO02.role_in_the_claim,
            MO02.individual_business_indicator,
            MO02.business_name,
            MO02.last_name,
            MO02.first_name,
            MO02.middle_name,
            MO02.date_of_birth_dob,
            MO02.gender,
            MO02.social_security_number_ssn,
            MO02.more_match_indicator,
            MO02.ssn_code,
            MO02.ssn_issued_from_date,
            MO02.ssn_issued_to_date,
            MO02.ssn_issuing_state,
            MO02.death_master_last_name,
            MO02.death_master_first_name,
            MO02.date_of_death,
            MO02.city_of_death,
            MO02.state_of_death,
            MO02.tax_identification_number_tin,
            MO02.tin_code,
            MO02.tin_issuing_city,
            MO02.tin_issuing_state,
            MO02.drivers_license_number,
            MO02.drivers_license_state,
            MO02.occupation,
            MO02.medical_professional_license,
            MO02.address_information_line_1,
            MO02.address_information_line_2,
            MO02.city,
            MO02.state,
            MO02.postal_code,
            MO02.country_code,
            MO02.home_telephone,
            MO02.more_match_indicator_2,
            MO02.business_telephone,
            MO02.cellular_telephone,
            MO02.more_match_indicator_3,
            MO02.pager_number,
            MO02.pager_pin,
            MEX2.party_subject_to_siu_investigation,
            MEX2.was_claim_or_part_of_claim_for_this_party_not_paid_after_investigation,
            MEX2.was_party_subject_to_an_enforcement_action_criminal_indictment_professional_disciplinary_action,
            MEX2.does_claim_for_this_party_meet_criteria_for_fraud_bureau_reporting,
            MEX2.date_of_death as date_of_death_2,
            MEX2.email_address,
            MEX2.drivers_license_class,
            MEX2.was_driver_distracted,
            MK02.individual_business_indicator as individual_business_indicator_2,
            MK02.business_name as business_name_2,
            MK02.last_name as last_name_2,
            MK02.first_name as first_name_2,
            MK02.middle_name as middle_name_2,
            MK02.date_of_birth_dob as date_of_birth_dob_2,
            MK02.gender as gender_2,
            MK02.social_security_number_ssn as social_security_number_ssn_2,
            MK02.more_match_indicator_4 as more_match_indicator_4_2,
            MK02.ssn_code as ssn_code_2,
            MK02.ssn_issued_from_date as ssn_issued_from_date_2,
            MK02.ssn_issued_to_date as ssn_issued_to_date_2,
            MK02.ssn_issuing_state as ssn_issuing_state_2,
            MK02.tax_identification_number_tin as tax_identification_number_tin_2,
            MK02.tin_code as tin_code_2,
            MK02.tin_issued_from_date as tin_issued_from_date_2,
            MK02.tin_issued_to_date as tin_issued_to_date_2,
            MK02.tin_issuing_state as tin_issuing_state_2,
            MK02.address_information_line_1 as address_information_line_1_2,
            MK02.address_information_line_2 as address_information_line_2_2,
            MK02.city as city_2,
            MK02.state as state_2,
            MK02.postal_code as postal_code_2,
            MK02.country_code as country_code_2,
            MK02.home_telephone as home_telephone_2,
            MK02.more_match_indicator_5,
            MK02.business_telephone as business_telephone_2,
            MK02.cell_telephone,
            MK02.more_match_indicator_6,
            MK02.email_address_of_alias_aka,
            MK02.drivers_license_number as drivers_license_number_2,
            MK02.drivers_license_state as drivers_license_state_2,
            MK02.drivers_license_class as drivers_license_class_2,
            MP02.adjusting_company_name,
            MP02.adjuster_last_name,
            MP02.adjuster_first_name,
            MP02.adjuster_middle_initial_name,
            MP02.adjuster_telephone_number,
            MP02.loss_type,
            MP02.claim_status,
            MP02.mortgage_loan_number,
            MP02.suit_indicator,
            MP02.building,
            MP02.contents,
            MP02.use_and_occupancy,
            MP02.stock,
            MP02.other,
            MP02.building_2,
            MP02.contents_2,
            MP02.use_and_occupancy_2,
            MP02.stock_2,
            MP02.other_2,
            MP02.building_3,
            MP02.contents_3,
            MP02.use_and_occupancy_3,
            MP02.stock_3,
            MP02.other_3,
            MP02.building_4,
            MP02.contents_4,
            MP02.use_and_occupancy_4,
            MP02.stock_4,
            MP02.other_4,
            MP02.type_of_property,
            MP02.other_property_description,
            MP02.vacant_under_construction_indicator,
            MP02.incendiary_fire_flag,
            MP02.location_of_theft,
            MP02.audio_visual,
            MP02.art_antique,
            MP02.cash,
            MP02.clothing,
            MP02.computer_equipment,
            MP02.furs,
            MP02.guns,
            MP02.jewelry,
            MP02.silverware,
            MP02.sports_equipment,
            MP02.tools,
            MP02.office_equipment,
            MP02.other_5,
            MP02.date_claim_closed,
            MP02.property_scheduled_indicator,
            MP02.property_scheduled_description,
            MP02.content_theft_type,
            MP14.adjuster_email_address,
            MSP2.role_in_the_claim as role_in_the_claim_3,
            MSP2.individual_business_indicator as individual_business_indicator_3,
            MSP2.business_name as business_name_3,
            MSP2.last_name as last_name_3,
            MSP2.first_name as first_name_3,
            MSP2.middle_name as middle_name_3,
            MSP2.date_of_birth_dob as date_of_birth_dob_3,
            MSP2.gender as gender_3,
            MSP2.social_security_number_ssn as social_security_number_ssn_3,
            MSP2.ssn_code as ssn_code_3,
            MSP2.ssn_issued_from_date as ssn_issued_from_date_3,
            MSP2.ssn_issued_to_date as ssn_issued_to_date_3,
            MSP2.ssn_issuing_state as ssn_issuing_state_3,
            MSP2.tax_identification_number_tin as tax_identification_number_tin_3,
            MSP2.tin_code as tin_code_3,
            MSP2.tin_issuing_city as tin_issuing_city_3,
            MSP2.tin_issuing_state as tin_issuing_state_3,
            MSP2.drivers_license_number as drivers_license_number_3,
            MSP2.drivers_license_state as drivers_license_state_3,
            MSP2.medical_professional_license as medical_professional_license_3,
            MSP2.address_information_line_1 as address_information_line_1_3,
            MSP2.address_information_line_2 as address_information_line_2_3,
            MSP2.city as city_3,
            MSP2.state as state_3,
            MSP2.postal_code as postal_code_3,
            MSP2.country_code as country_code_3,
            MSP2.home_telephone as home_telephone_3,
            MSP2.business_telephone as business_telephone_3,
            MSP2.cell_telephone as cell_telephone_3,
            MSP2.pager_number as pager_number_3,
            MSP2.pager_pin as pager_pin_3,
            MSP2.date_of_first_doctors_visit as date_of_first_doctors_visit_3,
            MV09.vin_of_salvaged_vehicle,
            MV09.more_match_indicator as more_match_indicator_7,
            MV09.vin_missing_indicator,
            MV09.engine_missing_indicator,
            MV09.transmission_missing_indicator,
            MV09.date_of_salvage,
            MV09.actual_cash_value_prior_to_loss,
            MV09.value_received_for_salvage,
            MV09.appraised_value_of_salvage,
            MV09.owner_retaining_salvage_indicator,
            MV09.individual_business_indicator as individual_business_indicator_4,
            MV09.buyers_business_name as business_name_4,
            MV09.buyers_last_name,
            MV09.buyers_first_name,
            MV09.buyers_middle_name,
            MV09.buyers_address_line_1,
            MV09.buyers_address_line_2,
            MV09.buyers_city,
            MV09.buyers_state,
            MV09.postal_code as buyers_postal_code,
            MV09.country_code as buyers_country_code,
            MV09.business_telephone as buyers_business_telephone,
            MV09.failed_vin as buyers_failed_vin

from        MO02
            left join
                MEX2
                on  MO02.response_id    = MEX2.response_id
                and MO02.index_MA01     = MEX2.index_MA01
                and MO02.index_MA03     = MEX2.index_MA03
                and MO02.index_MO02     = MEX2.index_MO02
            left join
                MK02
                on  MO02.response_id    = MK02.response_id
                and MO02.index_MA01     = MK02.index_MA01
                and MO02.index_MA03     = MK02.index_MA03
                and MO02.index_MO02     = MK02.index_MO02
            left join
                MP02
                on  MO02.response_id    = MP02.response_id
                and MO02.index_MA01     = MP02.index_MA01
                and MO02.index_MA03     = MP02.index_MA03
                and MO02.index_MO02     = MP02.index_MO02
            left join
                MP14
                on  MO02.response_id    = MP14.response_id
                and MO02.index_MA01     = MP14.index_MA01
                and MO02.index_MA03     = MP14.index_MA03
                and MO02.index_MO02     = MP14.index_MO02
            left join
                MSP2
                on  MO02.response_id    = MSP2.response_id
                and MO02.index_MA01     = MSP2.index_MA01
                and MO02.index_MA03     = MSP2.index_MA03
                and MO02.index_MO02     = MSP2.index_MO02
            left join
                MV09
                on  MO02.response_id    = MV09.response_id
                and MO02.index_MA01     = MV09.index_MA01
                and MO02.index_MA03     = MV09.index_MA03
                and MO02.index_MO02     = MV09.index_MO02
order by    1,2,3,4
;