create or replace table
    edwprodhh.iso.claimant_match_return_vehicle
as
with MV02 as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_ma03,
                index_mo02,
                index_mv02,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     55)),   '')     as adjusting_company_name,
                nullif(trim(substring(response_line,    66,     30)),   '')     as adjuster_last_name,
                nullif(trim(substring(response_line,    96,     20)),   '')     as adjuster_first_name,
                nullif(trim(substring(response_line,    116,    20)),   '')     as adjuster_middle_initial_name,
                nullif(trim(substring(response_line,    136,    10)),   '')     as adjuster_telephone_number,
                nullif(trim(substring(response_line,    146,    4)),    '')     as loss_type,
                nullif(trim(substring(response_line,    150,    4)),    '')     as coverage_type,
                nullif(trim(substring(response_line,    154,    4)),    '')     as vehicle_year,
                nullif(trim(substring(response_line,    158,    35)),   '')     as vehicle_make_description,
                nullif(trim(substring(response_line,    193,    35)),   '')     as vehicle_model_description,
                nullif(trim(substring(response_line,    228,    2)),    '')     as vehicle_style,
                nullif(trim(substring(response_line,    230,    2)),    '')     as vehicle_type,
                nullif(trim(substring(response_line,    232,    6)),    '')     as vehicle_color,
                nullif(trim(substring(response_line,    238,    20)),   '')     as vin,
                nullif(trim(substring(response_line,    258,    1)),    '')     as vin_validation,
                nullif(trim(substring(response_line,    259,    1)),    '')     as more_match_indicator,
                nullif(trim(substring(response_line,    260,    14)),   '')     as engine_serial_no,
                nullif(trim(substring(response_line,    274,    14)),   '')     as transmission_serial_no,
                nullif(trim(substring(response_line,    288,    14)),   '')     as chassis_serial_no,
                nullif(trim(substring(response_line,    302,    10)),   '')     as vehicle_odometer_reading,
                nullif(trim(substring(response_line,    312,    2)),    '')     as license_plate_type,
                nullif(trim(substring(response_line,    314,    10)),   '')     as license_plate_number,
                nullif(trim(substring(response_line,    324,    2)),    '')     as license_plate_state,
                nullif(trim(substring(response_line,    326,    4)),    '')     as last_year_registered,
                nullif(trim(substring(response_line,    330,    1)),    '')     as more_match_indicator_2,
                nullif(trim(substring(response_line,    331,    2)),    '')     as anti_theft_device_type,
                nullif(trim(substring(response_line,    333,    2)),    '')     as point_of_impact,
                nullif(trim(substring(response_line,    335,    1)),    '')     as driver_airbag_status,
                nullif(trim(substring(response_line,    336,    1)),    '')     as passenger_airbag_status,
                nullif(trim(substring(response_line,    337,    1)),    '')     as left_side_airbag_status,
                nullif(trim(substring(response_line,    338,    1)),    '')     as right_side_airbag_status,
                nullif(trim(substring(response_line,    339,    1)),    '')     as theft_type_indicator,
                nullif(trim(substring(response_line,    340,    3)),    '')     as claim_status,
                nullif(trim(substring(response_line,    343,    1)),    '')     as suit_indicator,
                nullif(trim(substring(response_line,    344,    11)),   '')     as filler,
                nullif(trim(substring(response_line,    355,    11)),   '')     as settlement_amount,
                nullif(trim(substring(response_line,    366,    8)),    '')     as date_claim_closed,
                nullif(trim(substring(response_line,    374,    20)),   '')     as failed_vin,
                nullif(trim(substring(response_line,    394,    2)),    '')     as filler,
                nullif(trim(substring(response_line,    396,    1)),    '')     as vehicle_disposition,
                nullif(trim(substring(response_line,    397,    11)),   '')     as estimate_amount,
                nullif(trim(substring(response_line,    408,    105)),  '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MV02'
)
select      MV02.response_id,
            MV02.index_MA01,
            MV02.index_MA03,
            MV02.index_MO02,
            MV02.index_MV02,

            MV02.adjusting_company_name,
            MV02.adjuster_last_name,
            MV02.adjuster_first_name,
            MV02.adjuster_middle_initial_name,
            MV02.adjuster_telephone_number,
            MV02.loss_type,
            MV02.coverage_type,
            MV02.vehicle_year,
            MV02.vehicle_make_description,
            MV02.vehicle_model_description,
            MV02.vehicle_style,
            MV02.vehicle_type,
            MV02.vehicle_color,
            MV02.vin,
            MV02.vin_validation,
            MV02.more_match_indicator,
            MV02.engine_serial_no,
            MV02.transmission_serial_no,
            MV02.chassis_serial_no,
            MV02.vehicle_odometer_reading,
            MV02.license_plate_type,
            MV02.license_plate_number,
            MV02.license_plate_state,
            MV02.last_year_registered,
            MV02.more_match_indicator_2,
            MV02.anti_theft_device_type,
            MV02.point_of_impact,
            MV02.driver_airbag_status,
            MV02.passenger_airbag_status,
            MV02.left_side_airbag_status,
            MV02.right_side_airbag_status,
            MV02.theft_type_indicator,
            MV02.claim_status,
            MV02.suit_indicator,
            MV02.settlement_amount,
            MV02.date_claim_closed,
            MV02.failed_vin,
            MV02.vehicle_disposition,
            MV02.estimate_amount

from        MV02
order by    1,2,3,4,5
;