create or replace table
    edwprodhh.iso.claimant_match_summary
as
with MS01 as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_mo01,
                index_ms01,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     11)),   '')     as iso_file_number_A1,
                nullif(trim(substring(response_line,    22,     10)),   '')     as match_reason_code_A1,
                nullif(trim(substring(response_line,    32,     11)),   '')     as iso_file_number_A2,
                nullif(trim(substring(response_line,    43,     10)),   '')     as match_reason_code_A2,
                nullif(trim(substring(response_line,    53,     11)),   '')     as iso_file_number_A3,
                nullif(trim(substring(response_line,    64,     10)),   '')     as match_reason_code_A3,
                nullif(trim(substring(response_line,    74,     11)),   '')     as iso_file_number_A4,
                nullif(trim(substring(response_line,    85,     10)),   '')     as match_reason_code_A4,
                nullif(trim(substring(response_line,    95,     11)),   '')     as iso_file_number_A5,
                nullif(trim(substring(response_line,    106,    10)),   '')     as match_reason_code_A5,
                nullif(trim(substring(response_line,    116,    11)),   '')     as iso_file_number_A6,
                nullif(trim(substring(response_line,    127,    10)),   '')     as match_reason_code_A6,
                nullif(trim(substring(response_line,    137,    11)),   '')     as iso_file_number_A7,
                nullif(trim(substring(response_line,    148,    10)),   '')     as match_reason_code_A7,
                nullif(trim(substring(response_line,    158,    11)),   '')     as iso_file_number_A8,
                nullif(trim(substring(response_line,    169,    10)),   '')     as match_reason_code_A8,
                nullif(trim(substring(response_line,    179,    11)),   '')     as iso_file_number_A9,
                nullif(trim(substring(response_line,    190,    10)),   '')     as match_reason_code_A9,
                nullif(trim(substring(response_line,    200,    11)),   '')     as iso_file_number_A10,
                nullif(trim(substring(response_line,    211,    10)),   '')     as match_reason_code_A10,
                nullif(trim(substring(response_line,    221,    11)),   '')     as iso_file_number_A11,
                nullif(trim(substring(response_line,    232,    10)),   '')     as match_reason_code_A11,
                nullif(trim(substring(response_line,    242,    11)),   '')     as iso_file_number_A12,
                nullif(trim(substring(response_line,    253,    10)),   '')     as match_reason_code_A12,
                nullif(trim(substring(response_line,    263,    11)),   '')     as iso_file_number_A13,
                nullif(trim(substring(response_line,    274,    10)),   '')     as match_reason_code_A13,
                nullif(trim(substring(response_line,    284,    11)),   '')     as iso_file_number_A14,
                nullif(trim(substring(response_line,    295,    10)),   '')     as match_reason_code_A14,
                nullif(trim(substring(response_line,    305,    11)),   '')     as iso_file_number_A15,
                nullif(trim(substring(response_line,    316,    10)),   '')     as match_reason_code_A15,
                nullif(trim(substring(response_line,    326,    11)),   '')     as iso_file_number_A16,
                nullif(trim(substring(response_line,    337,    10)),   '')     as match_reason_code_A16,
                nullif(trim(substring(response_line,    347,    11)),   '')     as iso_file_number_A17,
                nullif(trim(substring(response_line,    358,    10)),   '')     as match_reason_code_A17,
                nullif(trim(substring(response_line,    368,    11)),   '')     as iso_file_number_A18,
                nullif(trim(substring(response_line,    379,    10)),   '')     as match_reason_code_A18,
                nullif(trim(substring(response_line,    389,    11)),   '')     as iso_file_number_A19,
                nullif(trim(substring(response_line,    400,    10)),   '')     as match_reason_code_A19,
                nullif(trim(substring(response_line,    410,    11)),   '')     as iso_file_number_A20,
                nullif(trim(substring(response_line,    421,    10)),   '')     as match_reason_code_A20,
                nullif(trim(substring(response_line,    431,    11)),   '')     as iso_file_number_A21,
                nullif(trim(substring(response_line,    442,    10)),   '')     as match_reason_code_A21,
                nullif(trim(substring(response_line,    452,    61)),   '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MS01'
)
, MS01_MSUM as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_mo01,
                index_ms01,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     2)),    '')     as total_number_of_matches_by_loss_type,
                nullif(trim(substring(response_line,    13,     2)),    '')     as total_number_of_matches_with_siu_involvement,
                nullif(trim(substring(response_line,    15,     2)),    '')     as total_number_of_matches_by_name,
                nullif(trim(substring(response_line,    17,     2)),    '')     as total_number_of_matches_by_address,
                nullif(trim(substring(response_line,    19,     2)),    '')     as total_number_of_matches_by_ssn,
                nullif(trim(substring(response_line,    21,     2)),    '')     as total_number_of_matches_by_phone,
                nullif(trim(substring(response_line,    23,     2)),    '')     as total_number_of_matches_by_drivers_license,
                nullif(trim(substring(response_line,    25,     2)),    '')     as total_number_of_matches_by_vin,
                nullif(trim(substring(response_line,    27,     2)),    '')     as total_number_of_matches_by_license_plate,
                nullif(trim(substring(response_line,    29,     11)),   '')     as iso_file_number_B1,
                nullif(trim(substring(response_line,    40,     18)),   '')     as summary_code_B1,
                nullif(trim(substring(response_line,    58,     11)),   '')     as iso_file_number_B2,
                nullif(trim(substring(response_line,    69,     18)),   '')     as summary_code_B2,
                nullif(trim(substring(response_line,    87,     11)),   '')     as iso_file_number_B3,
                nullif(trim(substring(response_line,    98,     18)),   '')     as summary_code_B3,
                nullif(trim(substring(response_line,    116,    11)),   '')     as iso_file_number_B4,
                nullif(trim(substring(response_line,    127,    18)),   '')     as summary_code_B4,
                nullif(trim(substring(response_line,    145,    11)),   '')     as iso_file_number_B5,
                nullif(trim(substring(response_line,    156,    18)),   '')     as summary_code_B5,
                nullif(trim(substring(response_line,    174,    11)),   '')     as iso_file_number_B6,
                nullif(trim(substring(response_line,    185,    18)),   '')     as summary_code_B6,
                nullif(trim(substring(response_line,    203,    11)),   '')     as iso_file_number_B7,
                nullif(trim(substring(response_line,    214,    18)),   '')     as summary_code_B7,
                nullif(trim(substring(response_line,    232,    11)),   '')     as iso_file_number_B8,
                nullif(trim(substring(response_line,    243,    18)),   '')     as summary_code_B8,
                nullif(trim(substring(response_line,    261,    11)),   '')     as iso_file_number_B9,
                nullif(trim(substring(response_line,    272,    18)),   '')     as summary_code_B9,
                nullif(trim(substring(response_line,    290,    11)),   '')     as iso_file_number_B10,
                nullif(trim(substring(response_line,    301,    18)),   '')     as summary_code_B10,
                nullif(trim(substring(response_line,    319,    11)),   '')     as iso_file_number_B11,
                nullif(trim(substring(response_line,    330,    18)),   '')     as summary_code_B11,
                nullif(trim(substring(response_line,    348,    11)),   '')     as iso_file_number_B12,
                nullif(trim(substring(response_line,    359,    18)),   '')     as summary_code_B12,
                nullif(trim(substring(response_line,    377,    11)),   '')     as iso_file_number_B13,
                nullif(trim(substring(response_line,    388,    18)),   '')     as summary_code_B13,
                nullif(trim(substring(response_line,    406,    11)),   '')     as iso_file_number_B14,
                nullif(trim(substring(response_line,    417,    18)),   '')     as summary_code_B14,
                nullif(trim(substring(response_line,    435,    11)),   '')     as iso_file_number_B15,
                nullif(trim(substring(response_line,    446,    18)),   '')     as summary_code_B15,
                nullif(trim(substring(response_line,    464,    11)),   '')     as iso_file_number_B16,
                nullif(trim(substring(response_line,    475,    18)),   '')     as summary_code_B16,
                nullif(trim(substring(response_line,    493,    20)),   '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MSUM'
                and lag_match_indicator = 'MS01'
)
, MS01_MSKI as
(
    select      response_id,
                response_line,
                record_key,
                record_number,
                record_type,
                index_ma01,
                index_mo01,
                index_ms01,
                
                nullif(trim(substring(response_line,    1,      10)),   '')     as record_key,
                nullif(trim(substring(response_line,    11,     2)),    '')     as key_indicator_code_1,
                nullif(trim(substring(response_line,    13,     2)),    '')     as key_indicator_code_2,
                nullif(trim(substring(response_line,    15,     2)),    '')     as key_indicator_code_3,
                nullif(trim(substring(response_line,    17,     2)),    '')     as key_indicator_code_4,
                nullif(trim(substring(response_line,    19,     2)),    '')     as key_indicator_code_5,
                nullif(trim(substring(response_line,    21,     2)),    '')     as key_indicator_code_6,
                nullif(trim(substring(response_line,    23,     2)),    '')     as key_indicator_code_7,
                nullif(trim(substring(response_line,    25,     2)),    '')     as key_indicator_code_8,
                nullif(trim(substring(response_line,    27,     2)),    '')     as key_indicator_code_9,
                nullif(trim(substring(response_line,    29,     2)),    '')     as key_indicator_code_10,
                nullif(trim(substring(response_line,    31,     2)),    '')     as key_indicator_code_11,
                nullif(trim(substring(response_line,    33,     2)),    '')     as key_indicator_code_12,
                nullif(trim(substring(response_line,    35,     2)),    '')     as key_indicator_code_13,
                nullif(trim(substring(response_line,    37,     2)),    '')     as key_indicator_code_14,
                nullif(trim(substring(response_line,    39,     2)),    '')     as key_indicator_code_15,
                nullif(trim(substring(response_line,    41,     472)),  '')     as filler

    from        edwprodhh.iso.response_flat
    where       record_type = 'MSKI'
                and lag_match_indicator = 'MS01'
)
select      MS01.response_id,
            MS01.index_MA01,
            MS01.index_MO01,
            MS01.index_MS01,

            MS01.iso_file_number_A1,
            MS01.match_reason_code_A1,
            MS01.iso_file_number_A2,
            MS01.match_reason_code_A2,
            MS01.iso_file_number_A3,
            MS01.match_reason_code_A3,
            MS01.iso_file_number_A4,
            MS01.match_reason_code_A4,
            MS01.iso_file_number_A5,
            MS01.match_reason_code_A5,
            MS01.iso_file_number_A6,
            MS01.match_reason_code_A6,
            MS01.iso_file_number_A7,
            MS01.match_reason_code_A7,
            MS01.iso_file_number_A8,
            MS01.match_reason_code_A8,
            MS01.iso_file_number_A9,
            MS01.match_reason_code_A9,
            MS01.iso_file_number_A10,
            MS01.match_reason_code_A10,
            MS01.iso_file_number_A11,
            MS01.match_reason_code_A11,
            MS01.iso_file_number_A12,
            MS01.match_reason_code_A12,
            MS01.iso_file_number_A13,
            MS01.match_reason_code_A13,
            MS01.iso_file_number_A14,
            MS01.match_reason_code_A14,
            MS01.iso_file_number_A15,
            MS01.match_reason_code_A15,
            MS01.iso_file_number_A16,
            MS01.match_reason_code_A16,
            MS01.iso_file_number_A17,
            MS01.match_reason_code_A17,
            MS01.iso_file_number_A18,
            MS01.match_reason_code_A18,
            MS01.iso_file_number_A19,
            MS01.match_reason_code_A19,
            MS01.iso_file_number_A20,
            MS01.match_reason_code_A20,
            MS01.iso_file_number_A21,
            MS01.match_reason_code_A21,
            MS01_MSUM.total_number_of_matches_by_loss_type,
            MS01_MSUM.total_number_of_matches_with_siu_involvement,
            MS01_MSUM.total_number_of_matches_by_name,
            MS01_MSUM.total_number_of_matches_by_address,
            MS01_MSUM.total_number_of_matches_by_ssn,
            MS01_MSUM.total_number_of_matches_by_phone,
            MS01_MSUM.total_number_of_matches_by_drivers_license,
            MS01_MSUM.total_number_of_matches_by_vin,
            MS01_MSUM.total_number_of_matches_by_license_plate,
            MS01_MSUM.iso_file_number_B1,
            MS01_MSUM.summary_code_B1,
            MS01_MSUM.iso_file_number_B2,
            MS01_MSUM.summary_code_B2,
            MS01_MSUM.iso_file_number_B3,
            MS01_MSUM.summary_code_B3,
            MS01_MSUM.iso_file_number_B4,
            MS01_MSUM.summary_code_B4,
            MS01_MSUM.iso_file_number_B5,
            MS01_MSUM.summary_code_B5,
            MS01_MSUM.iso_file_number_B6,
            MS01_MSUM.summary_code_B6,
            MS01_MSUM.iso_file_number_B7,
            MS01_MSUM.summary_code_B7,
            MS01_MSUM.iso_file_number_B8,
            MS01_MSUM.summary_code_B8,
            MS01_MSUM.iso_file_number_B9,
            MS01_MSUM.summary_code_B9,
            MS01_MSUM.iso_file_number_B10,
            MS01_MSUM.summary_code_B10,
            MS01_MSUM.iso_file_number_B11,
            MS01_MSUM.summary_code_B11,
            MS01_MSUM.iso_file_number_B12,
            MS01_MSUM.summary_code_B12,
            MS01_MSUM.iso_file_number_B13,
            MS01_MSUM.summary_code_B13,
            MS01_MSUM.iso_file_number_B14,
            MS01_MSUM.summary_code_B14,
            MS01_MSUM.iso_file_number_B15,
            MS01_MSUM.summary_code_B15,
            MS01_MSUM.iso_file_number_B16,
            MS01_MSUM.summary_code_B16,
            MS01_MSKI.key_indicator_code_1,
            MS01_MSKI.key_indicator_code_2,
            MS01_MSKI.key_indicator_code_3,
            MS01_MSKI.key_indicator_code_4,
            MS01_MSKI.key_indicator_code_5,
            MS01_MSKI.key_indicator_code_6,
            MS01_MSKI.key_indicator_code_7,
            MS01_MSKI.key_indicator_code_8,
            MS01_MSKI.key_indicator_code_9,
            MS01_MSKI.key_indicator_code_10,
            MS01_MSKI.key_indicator_code_11,
            MS01_MSKI.key_indicator_code_12,
            MS01_MSKI.key_indicator_code_13,
            MS01_MSKI.key_indicator_code_14,
            MS01_MSKI.key_indicator_code_15

from        MS01
            left join
                MS01_MSUM
                on  MS01.response_id    = MS01_MSUM.response_id
                and MS01.index_MA01     = MS01_MSUM.index_MA01
                and MS01.index_MO01     = MS01_MSUM.index_MO01
                and MS01.index_MS01     = MS01_MSUM.index_MS01
            left join
                MS01_MSKI
                on  MS01.response_id    = MS01_MSKI.response_id
                and MS01.index_MA01     = MS01_MSKI.index_MA01
                and MS01.index_MO01     = MS01_MSKI.index_MO01
                and MS01.index_MS01     = MS01_MSKI.index_MS01
order by    1,2,3,4
;