create or replace table
    edwprodhh.iso.parse_match_report_flatten
as
with response_example_1 as
(
    select      '000001MH01H39500000HARRIS AND HARRIS                                      03262026                                                                                                                                                                                                                                                                                                                                                                                                                                              
                000002MA014K000611000IH39500001UMMCA1A1                      PAPP                  UMMCA1A1                      010120250000                                                                                                                                                                                           NY                                                                                                                                           000  N00             03252026           000000000          
                000003MO01CIISTABILE                       PETRO                                                                                                                                                                                                                                                                                 74-05 64TH LN                                                                                       GLENDALE                 NY            2097779981                                          
                000004MC01HARRIS AND HARRIS                                                                                                                      MPAYMPAYAUTO ACCIDENT                                                  000000000000000000000000000000000                                                                                                                                                                                                                                                                       
                000005MS014X000605849P         6J000608790N         6V000607142N                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                000006MSUM0101020000010000004X000605849LTP               6J000608790N                 6V000607142SIN                                                                                                                                                                                                                                                                                                                                                                                                                            
                000007MSKI0103                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                000008MA034X000605849CHUBB INSURANCE COMPANY OF NEW JERSEY                  4 PENN CENTER                                                                                       PHILADELPHIA             PA19103       9089033049HW0005173U                    CAPP0000000000000000  5550005173                    081120230000 00000000000                                                  TREE FALL DAMAGE                                                                                                                   
                000009MA04                                                                                                                             CA                                                                                                                                                                                                                                                                                                                                                                                       
                000010MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000011MO02CIBMALL ACTRESS LLC                                                                                                                                                                                                                                                                                                      12875 ALLSTREET                                                                                     TOMS RIVER               MA            2097779981                                        
                000012MC02CHUBB INSURANCE COMPANY OF NEW JERSEY                                                                                                  MPAYMPAYPROPERTY DAMAGE                                   00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000013MA036J000608790ANDOVER COMPANIES                                      95 OLD RIVER ROAD                                                                                   ANDOVER                  MA01810       8002250770HP14083295                    PPHO0000000000000000  CLM00059939                   021920260000 00000000000                                                  SERVLET ACCEPTANCE                                                                                                                 
                000014MA0415 THOMPSON LN                                                                                      SOMERVILLE               ME   04348-320                                                                                                                                                                                                                                                                                                                                                                           
                000015MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000016MO02INBJANICE MCGRATH AND DONALD MCGRATH                                                                                                                                                                                                                                                                                     15 THOMPSON LN                                                                                      SOMERVILLE               ME04348-320                         8657457566                  
                000017MO02CIISTABILE                       PETRO                                                                                                                                                                                                                                                                                   74-05 64TH LN                                                                                       GLENDALE                 NY11385                  3235551212                             
                000018MC02ANDOVER COMPANIES                                                                    DAVID WILSON                                      BODILIABOUCH, BANG, WHOA                                  00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000019MA036V000607142CHUBB INSURANCE COMPANY OF NEW JERSEY                  4 PENN CENTER                                                                                       PHILADELPHIA             PA19103       908903304969806638159                   PPHO0000000000000000  KDDTEST0987                   090620250000 00000000000                                                  TREE FALL DAMAGE                                                                                                                   
                000020MA04                                                                                                                             NJ                                                                                                                                                                                                                                                                                                                                                                                       
                000021MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000022MO02CIIBARBER                        JOHN                                    00001975                                                                                                                                                                                                                                        128 BROOKDALE CIR                                                                                   LEXINGTON                SC29072                             9872349873                  
                000023MV02                                                                                                                             0000000000COMPCOMP0000                                                                                                                                                0000000000              0000 0000     O   000000000000000000000000000000                       00000000000                                                                                                         
                000024MO02CDISTABILE                       PETRO                                                                                                                                                                                                                                                                                   74-05 64TH LN                                                                                       GLENDALE                 NY11385                                                         
                000025MC02CHUBB INSURANCE COMPANY OF NEW JERSEY                                                                                                  LIABLIABUNSPECIFIED                                       00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000026MA010E000611332IH39500001UMMCB2B2                      PAPP                  UMMCB2B2                      020120250000                                                                                                                                                                                           IL                                                                                                                                           000  N00             03252026           000000000          
                000027MO01CIIJACKSON                       JIMJON                                  00001990                                                                                                                                                                                                                                      3 E MAIN ST                                                                                         CHICAGO HEIGHTS          IL            9872349873                                          
                000028MC01HARRIS AND HARRIS                                                                                                                      MPAYMPAYAUTO ACCIDENT                                                  000000000000000000000000000000000                                                                                                                                                                                                                                                                       
                000029MS010D000599002P         3L000598837P         3U000598652P         3V000605403N P P     6G000609409P         6N000608134P         7F000598908P         7P000608107P         7T000599202P                                                                                                                                                                                                                                                                                                                                  
                000030MSUM0301010000090000000D000599002P                 3L000598837P                 3U000598652P                 3V000605403SIN P             6G000609409LTP               6N000608134LTP               7F000598908P                 7P000608107P                 7T000599202LTP                                                                                                                                                                                                                                              
                000031MSKI0103                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                000032MA030D000599002INFINITY INSURANCE COMPANY                             PO BOX 830807                                                                                       BIRMINGHAM               AL352830807   8007822040600006610011                  PAPP0000000000000000  253004550231                  082220250000 00000000000                                                  CLMT REAR-END INSD                                                                                                                 
                000033MA041420 W 24TH ST                                                                                      HOUSTON                  TXUS 77008                                                                                                                                                                                                                                                                                                                                                                               
                000034MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000035MO02CIIREDDY1                        LOKESH              A                   00001982M                                                                                                                                                                                                                                       1420 W 24TH ST                                                                                      HOUSTON                  TX77008    US            6543212345 9872349873                  
                000036MC02INFINITY INSURANCE COMPANY                             GENERIC                       KEMPER AUTO                             3416003518BODIBODITEST                                              00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000037MC02INFINITY INSURANCE COMPANY                             FIELDS                        VANCE                                   2817455585NFLTNFLTTEST                                              00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000038MA033L000598837INFINITY INSURANCE COMPANY                             PO BOX 830807                                                                                       BIRMINGHAM               AL352830807   8007822040600006610011                  PAPP0000000000000000  253004550061                  082120250000 00000000000                                                  CLMT REAR-END INSD                                                                                                                 
                000039MA041420 W 24TH ST                                                                                      HOUSTON                  TXUS 77008                                                                                                                                                                                                                                                                                                                                                                               
                000040MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000041MO02CIIREDDY1                        LOKESH              A                   00001982M                                                                                                                                                                                                                                       1420 W 24TH ST                                                                                      HOUSTON                  TX77008    US            6543212345 9872349873                  
                000042MC02INFINITY INSURANCE COMPANY                             FIELDS                        VANCE                                   2817455585NFLTNFLTTEST                                              00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000043MA033U000598652INFINITY INSURANCE COMPANY                             PO BOX 830807                                                                                       BIRMINGHAM               AL352830807   8007822040602001782011                  CAPP0000000000000000  253004549371                  081320250000 00000000000                                                  CLMT REAR-END INSD                                                                                                                 
                000044MA04157 RAINTREE DR                                                                                     LONGWOOD                 FLUS 32779                                                                                                                                                                                                                                                                                                                                                                               
                000045MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000046MO02CIIADAM1                         ALEX                                    00001993M                                                                                                                                                                                                                                       157 RAINTREE DR                                                                                     LONGWOOD                 FL32779    US 2303981111            9872349873                  
                000047MC02INFINITY INSURANCE COMPANY                             FIELDS                        VANCE                                   2817455585NFLTNFLTTEST                                              00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000048MA033V000605403ANDOVER COMPANIES                                      95 OLD RIVER ROAD                                                                                   ANDOVER                  MA018100000   508475330064360051RS                    PAPP0000000000000000  6436005167                    010120260000 00000000000                                                  TREE FALL DAMAGE                                                                                                                   
                000049MA04                                                                                                                             VT                                                                                                                                                                                                                                                                                                                                                                                       
                000050MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000051MO02CIIJACKSON                       JIMJON                                  00001990                                                                                                                                                                                                                                        3 E MAIN ST                                                                                         CHICAGO HEIGHTS          IL60411-416                         9872349873                  
                000052MC02ANDOVER COMPANIES                                                                                                                      BODIMPAYFALL INCIDENT                                     00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000053MO02CLIFLAPJACK                      FRED                                            M                                                                                                                                                                                                                                       3 MAIN ST                                                                                           HARTFORD                 CT06106       9872349873                                        
                000054MC02ANDOVER COMPANIES                                                                                                                      NFLTNFLTUNSPECIFIED                                       00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000055MA036G000609409TREXIS INSURANCE CORPORATION                           210 WESTWOOD PLACE                                                                                  BRENTWOOD                TN37027                 014432102                     PAPP0000000000000000  0000752917                    021320230000 00000000000                                                  TREE FALL DAMAGE                                                                                                                   
                000056MA04                                                                                                                             CT                                                                                                                                                                                                                                                                                                                                                                                       
                000057MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000058MO02CIIAOMGDR                        JOHN                                                                                                                                                                                                                                                                                    18654 ELM STREET                                                                                    EMEROSN                  OH            9872349873                                        
                000059MC02TREXIS INSURANCE CORPORATION                                                                                                           MPAYMPAYFALL INCIDENT                                     00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000060MA036N000608134CHUBB INSURANCE COMPANY OF NEW JERSEY                  4 PENN CENTER                                                                                       PHILADELPHIA             PA19103       908903304966006638159                   PPHO0000000000000000  CDTEST0987                    113020240000 00000000000                                                  ACCIDENT FALLING APART                                                                                                             
                000061MA04                                                                                                                             CT                                                                                                                                                                                                                                                                                                                                                                                       
                000062MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000063MO02INIBONKADOODLE                   BILL                                                                                                                                                                                                                                                                                    3 S MAIN ST                                                                                         ALBION                   NY14411-144                                                     
                000064MO02CLIBONKADOODLE                   BILL                                                                                                                                                                                                                                                                                    3 S MAIN ST                                                                                         ALBION                   NY14411                             9872349873                  
                000065MC02CHUBB INSURANCE COMPANY OF NEW JERSEY                                                                                                  MPAYLIABUNSPECIFIED                                       00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000066MA037F000598908KEMPER PREFERRED                                       12926 GRAN BAY PARKWAY W                                                                            JACKSONVILLE             FL32258       904245560010002049011                   PAPP0000000000000000  255004949641                  070120250000 00000000000                                                  BOTH PARTIES BACKING                                                                                                               
                000067MA04HUMBOLDT AVE N                                                                                      MINNEAPOLIS              MNUS                                                                                                                                                                                                                                                                                                                                                                                     
                000068MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000069MO02CIIBUST1                         BUEHLER                                 00001970M                                                                                                                                                                                                                                       HUMBOLDT AVE N                                                                                      MINNEAPOLIS              MN         US                       9872349873                  
                000070MC02KEMPER PREFERRED                                       CCMT1RP5                      CLAIM REP                               8005553241NFLTNFLTTEST                                              00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000071MA037P000608107CHUBB INSURANCE COMPANY OF NEW JERSEY                  4 PENN CENTER                                                                                       PHILADELPHIA             PA19103       9089033049PA53118801                    PAPP0000000000000000  03300005167                   101020250000 00000000000                                                  FALL ACCIDENTAL                                                                                                                    
                000072MA04                                                                                                                             CT                                                                                                                                                                                                                                                                                                                                                                                       
                000073MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000074MO02CIIPHILLIPSON                    PHIL                                    00001990                                                                                                                                                                                                                                        3 MAIN ST                                                                                           HARTFORD                 CT06106                             9872349873                  
                000075MC02CHUBB INSURANCE COMPANY OF NEW JERSEY                                                                                                  OTAUMPAYUNSPECIFIED                                       00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                   Y                                                                                                                    
                000076MC02CHUBB INSURANCE COMPANY OF NEW JERSEY                  TEST1                         TEST2                                             BODINFLTFALL INCIDENT                                     00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000077MC02CHUBB INSURANCE COMPANY OF NEW JERSEY                                                                                                  PRPDPRPDUNSPECIFIED                                       00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000078MA037T000599202KEMPER PREFERRED                                       12926 GRAN BAY PARKWAY W                                                                            JACKSONVILLE             FL32258       904245560011558599011                   PAPP0000000000000000  255004961421                  081420250000 00000000000                                                  BOTH PARTIES BACKING                                                                                                               
                000079MA04908 SPRINGHILL DR                                                                                   COAL CITY                ILUS 60416-390                                                                                                                                                                                                                                                                                                                                                                           
                000080MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000081MO02CIIFRENDLING1                    ROBERT              A                   00001959M                                                                                                                                                                                                                                       908 SPRINGHILL DR                                                                                   COAL CITY                IL60416-390US 9042450000            9872349873                  
                000082MC02KEMPER PREFERRED                                       HOLLY                         TINA                                    8005937851BODIBODITEST                                              00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000083MC02KEMPER PREFERRED                                       HOLLY                         TINA                                    8005937851MPAYMPAYTEST                                              00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000084MA018P000610660IH39500001UMMCD4D4                      PAPP                  UMMCD4D4                      040120250000                                                                                                                                                                                           TX                                                                                                                                           000  N00             03252026           000000000          
                000085MO01CIIZAMBRANO SANTOS               YUMAIKEL                                00001988                                                                                                                                                                                                                                      8955 BROADWAY ST.                                 UNIT 10173                                        HOUSTON                  TX77061                                                           
                000086MC01HARRIS AND HARRIS                                                                                                                      MPAYMPAYAUTO ACCIDENT                                                  000000000000000000000000000000000                                                                                                                                                                                                                                                                       
                000087MS010J000608699N                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                000088MSUM0000010000000000000J000608699N                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                000089MSKI03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                000090MA030J000608699CHUBB INSURANCE COMPANY OF NEW JERSEY                  4 PENN CENTER                                                                                       PHILADELPHIA             PA19103       9089033049DDTEST09833                   PAPP0000000000000000  CDTEST09833                   030120260000 00000000000                                                  TREE FALL DAMAGE                                                                                                                   
                000091MA04                                                                                                                             NJ                                                                                                                                                                                                                                                                                                                                                                                       
                000092MA08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                000093MO02CIIZAMBRANO SANTOS               YUMAIKEL                                00001988                                                                                                                                                                                                                                        8955 BROADWAY ST.                                 UNIT 10173                                        HOUSTON                  TX77061                                                         
                000094MC02CHUBB INSURANCE COMPANY OF NEW JERSEY                                                                                                  BODINFLTPROPERTY DAMAGE                                   00   O  00   000000000000000000000000000000000        000000000000000000000          00000000                                                                                                                                                                                                                        
                000095MZ01000095000000095
                ' as raw_response
)
, response_example_2 as
(
    select      '000001MH01
                000002MA01
                000003MA05
                000004MA07
                000005MO01
                000006MEX1
                000007MK01
                000008MSP1
                000009MEX1
                000010MK01
                000011MSP1
                000012MK01
                000013MACL
                000014MSP1
                000015MK01
                000016MC01
                000017MV01
                000018MS01
                000019MSUM
                000020MSKI
                000021MS02
                000022MSUM
                000023MSKI
                000024MO01
                000025MC01
                000026MEX3
                000027MEX4
                000028MCMS
                000029MS01
                000030MSUM
                000031MSKI
                000032MO01
                000033MS01
                000034MSUM
                000035MSKI
                000036MA03
                000037MA04
                000038MA06
                000039MO02
                000040MEX2
                000041MK02
                000042MP02
                000043MP14
                000044MA01
                000045MO01
                000046MV01
                000047MEX3
                000048MEX4
                000049MS01
                000050MSUM
                000051MO01
                000052MC01
                000053MEX3
                000054MCMS
                000055MS01
                000056MSUM
                000057MA01
                000058MO01
                000059MS01
                000060MSUM
                000061MSKI
                000062MO01
                000063MC01
                000064MS01
                000065MSUM
                000066MSKI
                000067MA03
                000068MA04
                000069MO02
                000070MC02
                000071MO02
                000072MC02
                000073MA03
                000074MA04
                000075MO02
                000076MK02
                000077MO02
                000078MZ01' as raw_response
)
, response_split as
(
    select      nullif(trim(split.value), '') as response_line
    from        response_example_1,
    -- from        response_example_2,
                lateral split_to_table(raw_response, '\n') as split
    where       response_line is not null
)
, response_keys as
(
    select      'ABC'                                                                   as response_id,
                response_line                                                           as response_line,
                substring(response_line,    1,      10)                                 as record_key,
                substring(response_line,    1,      6)                                  as record_number,
                substring(response_line,    7,      4)                                  as record_type,
                row_number() over (partition by response_id order by record_number asc) as index
    from        response_split
    order by    3
)
, lvl1 as
(
    select      *,
                max(case when record_type = 'MA01' then index end) over (partition by response_id order by index asc) as index_ma01
    from        response_keys
)
, lvl2 as
(
    select      *,
                max(case when record_type = 'MO01' then index end) over (partition by response_id, index_ma01 order by index asc) as index_mo01,
                max(case when record_type = 'MA03' then index end) over (partition by response_id, index_ma01 order by index asc) as index_ma03
    from        lvl1
)
, lvl3 as
(
    select      *,

                max(case when record_type = 'MSP1' then index end) over (partition by response_id, index_ma01, index_mo01 order by index asc) as index_msp1,
                max(case when record_type = 'MACL' then index end) over (partition by response_id, index_ma01, index_mo01 order by index asc) as index_macl,
                max(case when record_type = 'MS01' then index end) over (partition by response_id, index_ma01, index_mo01 order by index asc) as index_ms01,
                max(case when record_type = 'MS02' then index end) over (partition by response_id, index_ma01, index_mo01 order by index asc) as index_ms02,

                max(case when record_type = 'MO02' then index end) over (partition by response_id, index_ma01, index_ma03 order by index asc) as index_mo02,

                coalesce(
                    case when record_type in ('MO01', 'MSP1', 'MACL') then record_type else NULL end,
                    lag(case when record_type in ('MO01', 'MSP1', 'MACL') then record_type else NULL end) ignore nulls over (partition by response_id, index_ma01, index_mo01 order by index asc)
                )   as lag_party_indicator,

                coalesce(
                    case when record_type in ('MC01', 'MV01') then record_type else NULL end,
                    lag(case when record_type in ('MC01', 'MV01') then record_type else NULL end) ignore nulls over (partition by response_id, index_ma01, index_mo01 order by index asc)
                )   as lag_coverage_indicator,

                coalesce(
                    case when record_type in ('MS01', 'MS02') then record_type else NULL end,
                    lag(case when record_type in ('MS01', 'MS02') then record_type else NULL end) ignore nulls over (partition by response_id, index_ma01, index_mo01 order by index asc)
                )   as lag_match_indicator

    from        lvl2
)
select      *
from        lvl3
order by    response_id, index
;