create or replace procedure
    edwprodhh.iso.update_claimant_match_summary()
returns     boolean
language    sql
as
begin

    insert into
        edwprodhh.iso.claimant_match_summary
    (
        RESPONSE_ID,
        INDEX_MA01,
        INDEX_MO01,
        INDEX_MS01,
        ISO_FILE_NUMBER_A1,
        MATCH_REASON_CODE_A1,
        ISO_FILE_NUMBER_A2,
        MATCH_REASON_CODE_A2,
        ISO_FILE_NUMBER_A3,
        MATCH_REASON_CODE_A3,
        ISO_FILE_NUMBER_A4,
        MATCH_REASON_CODE_A4,
        ISO_FILE_NUMBER_A5,
        MATCH_REASON_CODE_A5,
        ISO_FILE_NUMBER_A6,
        MATCH_REASON_CODE_A6,
        ISO_FILE_NUMBER_A7,
        MATCH_REASON_CODE_A7,
        ISO_FILE_NUMBER_A8,
        MATCH_REASON_CODE_A8,
        ISO_FILE_NUMBER_A9,
        MATCH_REASON_CODE_A9,
        ISO_FILE_NUMBER_A10,
        MATCH_REASON_CODE_A10,
        ISO_FILE_NUMBER_A11,
        MATCH_REASON_CODE_A11,
        ISO_FILE_NUMBER_A12,
        MATCH_REASON_CODE_A12,
        ISO_FILE_NUMBER_A13,
        MATCH_REASON_CODE_A13,
        ISO_FILE_NUMBER_A14,
        MATCH_REASON_CODE_A14,
        ISO_FILE_NUMBER_A15,
        MATCH_REASON_CODE_A15,
        ISO_FILE_NUMBER_A16,
        MATCH_REASON_CODE_A16,
        ISO_FILE_NUMBER_A17,
        MATCH_REASON_CODE_A17,
        ISO_FILE_NUMBER_A18,
        MATCH_REASON_CODE_A18,
        ISO_FILE_NUMBER_A19,
        MATCH_REASON_CODE_A19,
        ISO_FILE_NUMBER_A20,
        MATCH_REASON_CODE_A20,
        ISO_FILE_NUMBER_A21,
        MATCH_REASON_CODE_A21,
        TOTAL_NUMBER_OF_MATCHES_BY_LOSS_TYPE,
        TOTAL_NUMBER_OF_MATCHES_WITH_SIU_INVOLVEMENT,
        TOTAL_NUMBER_OF_MATCHES_BY_NAME,
        TOTAL_NUMBER_OF_MATCHES_BY_ADDRESS,
        TOTAL_NUMBER_OF_MATCHES_BY_SSN,
        TOTAL_NUMBER_OF_MATCHES_BY_PHONE,
        TOTAL_NUMBER_OF_MATCHES_BY_DRIVERS_LICENSE,
        TOTAL_NUMBER_OF_MATCHES_BY_VIN,
        TOTAL_NUMBER_OF_MATCHES_BY_LICENSE_PLATE,
        ISO_FILE_NUMBER_B1,
        SUMMARY_CODE_B1,
        ISO_FILE_NUMBER_B2,
        SUMMARY_CODE_B2,
        ISO_FILE_NUMBER_B3,
        SUMMARY_CODE_B3,
        ISO_FILE_NUMBER_B4,
        SUMMARY_CODE_B4,
        ISO_FILE_NUMBER_B5,
        SUMMARY_CODE_B5,
        ISO_FILE_NUMBER_B6,
        SUMMARY_CODE_B6,
        ISO_FILE_NUMBER_B7,
        SUMMARY_CODE_B7,
        ISO_FILE_NUMBER_B8,
        SUMMARY_CODE_B8,
        ISO_FILE_NUMBER_B9,
        SUMMARY_CODE_B9,
        ISO_FILE_NUMBER_B10,
        SUMMARY_CODE_B10,
        ISO_FILE_NUMBER_B11,
        SUMMARY_CODE_B11,
        ISO_FILE_NUMBER_B12,
        SUMMARY_CODE_B12,
        ISO_FILE_NUMBER_B13,
        SUMMARY_CODE_B13,
        ISO_FILE_NUMBER_B14,
        SUMMARY_CODE_B14,
        ISO_FILE_NUMBER_B15,
        SUMMARY_CODE_B15,
        ISO_FILE_NUMBER_B16,
        SUMMARY_CODE_B16,
        KEY_INDICATOR_CODE_1,
        KEY_INDICATOR_CODE_2,
        KEY_INDICATOR_CODE_3,
        KEY_INDICATOR_CODE_4,
        KEY_INDICATOR_CODE_5,
        KEY_INDICATOR_CODE_6,
        KEY_INDICATOR_CODE_7,
        KEY_INDICATOR_CODE_8,
        KEY_INDICATOR_CODE_9,
        KEY_INDICATOR_CODE_10,
        KEY_INDICATOR_CODE_11,
        KEY_INDICATOR_CODE_12,
        KEY_INDICATOR_CODE_13,
        KEY_INDICATOR_CODE_14,
        KEY_INDICATOR_CODE_15
    )
    with filtered as
    (
        select      *
        from        edwprodhh.iso.response_flat
        where       index_ms01 is not null
                    and response_id not in (select response_id from edwprodhh.iso.claimant_match_summary)
    )
    , MS01 as
    (
        select      response_id,
                    response_body,
                    record_key,
                    record_number,
                    record_type,
                    index_ma01,
                    index_mo01,
                    index_ms01,
                    
                    nullif(trim(substring(response_body,    1,      10)),   '')     as record_key,
                    nullif(trim(substring(response_body,    11,     11)),   '')     as iso_file_number_A1,
                    nullif(trim(substring(response_body,    22,     10)),   '')     as match_reason_code_A1,
                    nullif(trim(substring(response_body,    32,     11)),   '')     as iso_file_number_A2,
                    nullif(trim(substring(response_body,    43,     10)),   '')     as match_reason_code_A2,
                    nullif(trim(substring(response_body,    53,     11)),   '')     as iso_file_number_A3,
                    nullif(trim(substring(response_body,    64,     10)),   '')     as match_reason_code_A3,
                    nullif(trim(substring(response_body,    74,     11)),   '')     as iso_file_number_A4,
                    nullif(trim(substring(response_body,    85,     10)),   '')     as match_reason_code_A4,
                    nullif(trim(substring(response_body,    95,     11)),   '')     as iso_file_number_A5,
                    nullif(trim(substring(response_body,    106,    10)),   '')     as match_reason_code_A5,
                    nullif(trim(substring(response_body,    116,    11)),   '')     as iso_file_number_A6,
                    nullif(trim(substring(response_body,    127,    10)),   '')     as match_reason_code_A6,
                    nullif(trim(substring(response_body,    137,    11)),   '')     as iso_file_number_A7,
                    nullif(trim(substring(response_body,    148,    10)),   '')     as match_reason_code_A7,
                    nullif(trim(substring(response_body,    158,    11)),   '')     as iso_file_number_A8,
                    nullif(trim(substring(response_body,    169,    10)),   '')     as match_reason_code_A8,
                    nullif(trim(substring(response_body,    179,    11)),   '')     as iso_file_number_A9,
                    nullif(trim(substring(response_body,    190,    10)),   '')     as match_reason_code_A9,
                    nullif(trim(substring(response_body,    200,    11)),   '')     as iso_file_number_A10,
                    nullif(trim(substring(response_body,    211,    10)),   '')     as match_reason_code_A10,
                    nullif(trim(substring(response_body,    221,    11)),   '')     as iso_file_number_A11,
                    nullif(trim(substring(response_body,    232,    10)),   '')     as match_reason_code_A11,
                    nullif(trim(substring(response_body,    242,    11)),   '')     as iso_file_number_A12,
                    nullif(trim(substring(response_body,    253,    10)),   '')     as match_reason_code_A12,
                    nullif(trim(substring(response_body,    263,    11)),   '')     as iso_file_number_A13,
                    nullif(trim(substring(response_body,    274,    10)),   '')     as match_reason_code_A13,
                    nullif(trim(substring(response_body,    284,    11)),   '')     as iso_file_number_A14,
                    nullif(trim(substring(response_body,    295,    10)),   '')     as match_reason_code_A14,
                    nullif(trim(substring(response_body,    305,    11)),   '')     as iso_file_number_A15,
                    nullif(trim(substring(response_body,    316,    10)),   '')     as match_reason_code_A15,
                    nullif(trim(substring(response_body,    326,    11)),   '')     as iso_file_number_A16,
                    nullif(trim(substring(response_body,    337,    10)),   '')     as match_reason_code_A16,
                    nullif(trim(substring(response_body,    347,    11)),   '')     as iso_file_number_A17,
                    nullif(trim(substring(response_body,    358,    10)),   '')     as match_reason_code_A17,
                    nullif(trim(substring(response_body,    368,    11)),   '')     as iso_file_number_A18,
                    nullif(trim(substring(response_body,    379,    10)),   '')     as match_reason_code_A18,
                    nullif(trim(substring(response_body,    389,    11)),   '')     as iso_file_number_A19,
                    nullif(trim(substring(response_body,    400,    10)),   '')     as match_reason_code_A19,
                    nullif(trim(substring(response_body,    410,    11)),   '')     as iso_file_number_A20,
                    nullif(trim(substring(response_body,    421,    10)),   '')     as match_reason_code_A20,
                    nullif(trim(substring(response_body,    431,    11)),   '')     as iso_file_number_A21,
                    nullif(trim(substring(response_body,    442,    10)),   '')     as match_reason_code_A21,
                    nullif(trim(substring(response_body,    452,    61)),   '')     as filler

        from        filtered
        where       record_type = 'MS01'
    )
    , MS01_MSUM as
    (
        select      response_id,
                    response_body,
                    record_key,
                    record_number,
                    record_type,
                    index_ma01,
                    index_mo01,
                    index_ms01,
                    
                    nullif(trim(substring(response_body,    1,      10)),   '')     as record_key,
                    nullif(trim(substring(response_body,    11,     2)),    '')     as total_number_of_matches_by_loss_type,
                    nullif(trim(substring(response_body,    13,     2)),    '')     as total_number_of_matches_with_siu_involvement,
                    nullif(trim(substring(response_body,    15,     2)),    '')     as total_number_of_matches_by_name,
                    nullif(trim(substring(response_body,    17,     2)),    '')     as total_number_of_matches_by_address,
                    nullif(trim(substring(response_body,    19,     2)),    '')     as total_number_of_matches_by_ssn,
                    nullif(trim(substring(response_body,    21,     2)),    '')     as total_number_of_matches_by_phone,
                    nullif(trim(substring(response_body,    23,     2)),    '')     as total_number_of_matches_by_drivers_license,
                    nullif(trim(substring(response_body,    25,     2)),    '')     as total_number_of_matches_by_vin,
                    nullif(trim(substring(response_body,    27,     2)),    '')     as total_number_of_matches_by_license_plate,
                    nullif(trim(substring(response_body,    29,     11)),   '')     as iso_file_number_B1,
                    nullif(trim(substring(response_body,    40,     18)),   '')     as summary_code_B1,
                    nullif(trim(substring(response_body,    58,     11)),   '')     as iso_file_number_B2,
                    nullif(trim(substring(response_body,    69,     18)),   '')     as summary_code_B2,
                    nullif(trim(substring(response_body,    87,     11)),   '')     as iso_file_number_B3,
                    nullif(trim(substring(response_body,    98,     18)),   '')     as summary_code_B3,
                    nullif(trim(substring(response_body,    116,    11)),   '')     as iso_file_number_B4,
                    nullif(trim(substring(response_body,    127,    18)),   '')     as summary_code_B4,
                    nullif(trim(substring(response_body,    145,    11)),   '')     as iso_file_number_B5,
                    nullif(trim(substring(response_body,    156,    18)),   '')     as summary_code_B5,
                    nullif(trim(substring(response_body,    174,    11)),   '')     as iso_file_number_B6,
                    nullif(trim(substring(response_body,    185,    18)),   '')     as summary_code_B6,
                    nullif(trim(substring(response_body,    203,    11)),   '')     as iso_file_number_B7,
                    nullif(trim(substring(response_body,    214,    18)),   '')     as summary_code_B7,
                    nullif(trim(substring(response_body,    232,    11)),   '')     as iso_file_number_B8,
                    nullif(trim(substring(response_body,    243,    18)),   '')     as summary_code_B8,
                    nullif(trim(substring(response_body,    261,    11)),   '')     as iso_file_number_B9,
                    nullif(trim(substring(response_body,    272,    18)),   '')     as summary_code_B9,
                    nullif(trim(substring(response_body,    290,    11)),   '')     as iso_file_number_B10,
                    nullif(trim(substring(response_body,    301,    18)),   '')     as summary_code_B10,
                    nullif(trim(substring(response_body,    319,    11)),   '')     as iso_file_number_B11,
                    nullif(trim(substring(response_body,    330,    18)),   '')     as summary_code_B11,
                    nullif(trim(substring(response_body,    348,    11)),   '')     as iso_file_number_B12,
                    nullif(trim(substring(response_body,    359,    18)),   '')     as summary_code_B12,
                    nullif(trim(substring(response_body,    377,    11)),   '')     as iso_file_number_B13,
                    nullif(trim(substring(response_body,    388,    18)),   '')     as summary_code_B13,
                    nullif(trim(substring(response_body,    406,    11)),   '')     as iso_file_number_B14,
                    nullif(trim(substring(response_body,    417,    18)),   '')     as summary_code_B14,
                    nullif(trim(substring(response_body,    435,    11)),   '')     as iso_file_number_B15,
                    nullif(trim(substring(response_body,    446,    18)),   '')     as summary_code_B15,
                    nullif(trim(substring(response_body,    464,    11)),   '')     as iso_file_number_B16,
                    nullif(trim(substring(response_body,    475,    18)),   '')     as summary_code_B16,
                    nullif(trim(substring(response_body,    493,    20)),   '')     as filler

        from        filtered
        where       record_type = 'MSUM'
                    and lag_match_indicator = 'MS01'
    )
    , MS01_MSKI as
    (
        select      response_id,
                    response_body,
                    record_key,
                    record_number,
                    record_type,
                    index_ma01,
                    index_mo01,
                    index_ms01,
                    
                    nullif(trim(substring(response_body,    1,      10)),   '')     as record_key,
                    nullif(trim(substring(response_body,    11,     2)),    '')     as key_indicator_code_1,
                    nullif(trim(substring(response_body,    13,     2)),    '')     as key_indicator_code_2,
                    nullif(trim(substring(response_body,    15,     2)),    '')     as key_indicator_code_3,
                    nullif(trim(substring(response_body,    17,     2)),    '')     as key_indicator_code_4,
                    nullif(trim(substring(response_body,    19,     2)),    '')     as key_indicator_code_5,
                    nullif(trim(substring(response_body,    21,     2)),    '')     as key_indicator_code_6,
                    nullif(trim(substring(response_body,    23,     2)),    '')     as key_indicator_code_7,
                    nullif(trim(substring(response_body,    25,     2)),    '')     as key_indicator_code_8,
                    nullif(trim(substring(response_body,    27,     2)),    '')     as key_indicator_code_9,
                    nullif(trim(substring(response_body,    29,     2)),    '')     as key_indicator_code_10,
                    nullif(trim(substring(response_body,    31,     2)),    '')     as key_indicator_code_11,
                    nullif(trim(substring(response_body,    33,     2)),    '')     as key_indicator_code_12,
                    nullif(trim(substring(response_body,    35,     2)),    '')     as key_indicator_code_13,
                    nullif(trim(substring(response_body,    37,     2)),    '')     as key_indicator_code_14,
                    nullif(trim(substring(response_body,    39,     2)),    '')     as key_indicator_code_15,
                    nullif(trim(substring(response_body,    41,     472)),  '')     as filler

        from        filtered
        where       record_type = 'MSKI'
                    and lag_match_indicator = 'MS01'
    )
    select      MS01.response_id,
                MS01.index_MA01,
                MS01.index_MO01,
                MS01.index_MS01,

                MS01.iso_file_number_A1,
                MS01.match_reason_code_A1,
                MS01.iso_file_number_A2,
                MS01.match_reason_code_A2,
                MS01.iso_file_number_A3,
                MS01.match_reason_code_A3,
                MS01.iso_file_number_A4,
                MS01.match_reason_code_A4,
                MS01.iso_file_number_A5,
                MS01.match_reason_code_A5,
                MS01.iso_file_number_A6,
                MS01.match_reason_code_A6,
                MS01.iso_file_number_A7,
                MS01.match_reason_code_A7,
                MS01.iso_file_number_A8,
                MS01.match_reason_code_A8,
                MS01.iso_file_number_A9,
                MS01.match_reason_code_A9,
                MS01.iso_file_number_A10,
                MS01.match_reason_code_A10,
                MS01.iso_file_number_A11,
                MS01.match_reason_code_A11,
                MS01.iso_file_number_A12,
                MS01.match_reason_code_A12,
                MS01.iso_file_number_A13,
                MS01.match_reason_code_A13,
                MS01.iso_file_number_A14,
                MS01.match_reason_code_A14,
                MS01.iso_file_number_A15,
                MS01.match_reason_code_A15,
                MS01.iso_file_number_A16,
                MS01.match_reason_code_A16,
                MS01.iso_file_number_A17,
                MS01.match_reason_code_A17,
                MS01.iso_file_number_A18,
                MS01.match_reason_code_A18,
                MS01.iso_file_number_A19,
                MS01.match_reason_code_A19,
                MS01.iso_file_number_A20,
                MS01.match_reason_code_A20,
                MS01.iso_file_number_A21,
                MS01.match_reason_code_A21,
                MS01_MSUM.total_number_of_matches_by_loss_type,
                MS01_MSUM.total_number_of_matches_with_siu_involvement,
                MS01_MSUM.total_number_of_matches_by_name,
                MS01_MSUM.total_number_of_matches_by_address,
                MS01_MSUM.total_number_of_matches_by_ssn,
                MS01_MSUM.total_number_of_matches_by_phone,
                MS01_MSUM.total_number_of_matches_by_drivers_license,
                MS01_MSUM.total_number_of_matches_by_vin,
                MS01_MSUM.total_number_of_matches_by_license_plate,
                MS01_MSUM.iso_file_number_B1,
                MS01_MSUM.summary_code_B1,
                MS01_MSUM.iso_file_number_B2,
                MS01_MSUM.summary_code_B2,
                MS01_MSUM.iso_file_number_B3,
                MS01_MSUM.summary_code_B3,
                MS01_MSUM.iso_file_number_B4,
                MS01_MSUM.summary_code_B4,
                MS01_MSUM.iso_file_number_B5,
                MS01_MSUM.summary_code_B5,
                MS01_MSUM.iso_file_number_B6,
                MS01_MSUM.summary_code_B6,
                MS01_MSUM.iso_file_number_B7,
                MS01_MSUM.summary_code_B7,
                MS01_MSUM.iso_file_number_B8,
                MS01_MSUM.summary_code_B8,
                MS01_MSUM.iso_file_number_B9,
                MS01_MSUM.summary_code_B9,
                MS01_MSUM.iso_file_number_B10,
                MS01_MSUM.summary_code_B10,
                MS01_MSUM.iso_file_number_B11,
                MS01_MSUM.summary_code_B11,
                MS01_MSUM.iso_file_number_B12,
                MS01_MSUM.summary_code_B12,
                MS01_MSUM.iso_file_number_B13,
                MS01_MSUM.summary_code_B13,
                MS01_MSUM.iso_file_number_B14,
                MS01_MSUM.summary_code_B14,
                MS01_MSUM.iso_file_number_B15,
                MS01_MSUM.summary_code_B15,
                MS01_MSUM.iso_file_number_B16,
                MS01_MSUM.summary_code_B16,
                MS01_MSKI.key_indicator_code_1,
                MS01_MSKI.key_indicator_code_2,
                MS01_MSKI.key_indicator_code_3,
                MS01_MSKI.key_indicator_code_4,
                MS01_MSKI.key_indicator_code_5,
                MS01_MSKI.key_indicator_code_6,
                MS01_MSKI.key_indicator_code_7,
                MS01_MSKI.key_indicator_code_8,
                MS01_MSKI.key_indicator_code_9,
                MS01_MSKI.key_indicator_code_10,
                MS01_MSKI.key_indicator_code_11,
                MS01_MSKI.key_indicator_code_12,
                MS01_MSKI.key_indicator_code_13,
                MS01_MSKI.key_indicator_code_14,
                MS01_MSKI.key_indicator_code_15

    from        MS01
                left join
                    MS01_MSUM
                    on  MS01.response_id    = MS01_MSUM.response_id
                    and MS01.index_MA01     = MS01_MSUM.index_MA01
                    and MS01.index_MO01     = MS01_MSUM.index_MO01
                    and MS01.index_MS01     = MS01_MSUM.index_MS01
                left join
                    MS01_MSKI
                    on  MS01.response_id    = MS01_MSKI.response_id
                    and MS01.index_MA01     = MS01_MSKI.index_MA01
                    and MS01.index_MO01     = MS01_MSKI.index_MO01
                    and MS01.index_MS01     = MS01_MSKI.index_MS01
    order by    1,2,3,4
    ;


end
;



create or replace task
    edwprodhh.iso.sp_update_claimant_match_summary
    warehouse = analysis_wh
    after edwprodhh.iso.sp_update_response_flat
as
call edwprodhh.iso.update_claimant_match_summary();
;